<?php

   /**
    * Implements hook_install().
    */
    function ibanvalidator_install() {
        $ret = array();

        $spec = array(
            'type' => 'int',
            'size' => 'tiny',
            'not null' => FALSE,
            'description' => 'This field describes how a field is acting when it\'s part of a Spanish bank account (entity, office, CD or account)'
        );

        db_add_field( "webform_component", "esban_info", $spec );
    }

?>
